version: "3.0"

services:
  nginx:
    image: nginx
    build: ./requirements/nginx/
    container_name: nginx
    depends_on:
      - wordpress
    restart: on-failure
    networks:
      - inception
    ports:
      - "443:443"
    volumes:
      - wp-volume:/var/www/wordpress

  wordpress:
    image: wordpress
    build: ./requirements/wordpress/
    container_name: wordpress
    depends_on:
      - mariadb
    environment:
      MARIADB_DATABASE: "${MARIADB_DATABASE}"
      MARIADB_USER: "${MARIADB_USER}"
      MARIADB_PASSWORD: "${MARIADB_PASSWORD}"
      MARIADB_HOST: "${MARIADB_HOST}"
      ADMIN_EMAIL: "${ADMIN_EMAIL}"
      USER2: "${USER2}"
      USER2_EMAIL: "${USER2_EMAIL}"
    restart: on-failure
    networks:
      - inception
    volumes:
      - wp-volume:/var/www/wordpress

  mariadb:
    image: mariadb
    build: ./requirements/mariadb/
    container_name: mariadb
    environment:
      MARIADB_ROOT_USER: "${MARIADB_ROOT_USER}"
      MARIADB_ROOT_PASSWORD: "${MARIADB_ROOT_PASSWORD}"
      MARIADB_DATABASE: "${MARIADB_DATABASE}"
      MARIADB_USER: "${MARIADB_USER}"
      MARIADB_PASSWORD: "${MARIADB_PASSWORD}"
    restart: on-failure
    networks:
      - inception
    volumes:
      - mariadb-volume:/var/lib/mysql

networks:
  inception:
    name: inception

volumes:
  wp-volume:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: "${VOLUME_PATH}/wordpress"

  mariadb-volume:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: "${VOLUME_PATH}/mariadb"
