version: '3.9'

services:
  mariadb:
    build: ./requirements/mariadb/
    container_name: mariadb
    environment:
      - MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      - MARIADB_DATABASE: ${MARIADB_DATABASE}
      - MARIADB_USER: ${MARIADB_USER}
      - MARIADB_PASSWORD: ${MARIADB_PASSWORD}
    restart: always
