version: "3.0"

services:
  mariadb:
    image: mariadb
    build: ./requirements/mariadb/
    container_name: mariadb
    environment:
      MARIADB_ROOT_PASSWORD: "${MARIADB_ROOT_PASSWORD}"
      MARIADB_DATABASE: "${MARIADB_DATABASE}"
      MARIADB_USER: "${MARIADB_USER}"
      MARIADB_PASSWORD: "${MARIADB_PASSWORD}"
    restart: on-failure
    networks:
      - inception

networks:
  inception:
    name: inception
