version: "3.0"

services:
  wordpress:
    image: wordpress
    build: ./requirements/wordpress/
    container_name: wordpress
    depends_on:
      - mariadb
    environment:
      WP_DB_NAME: "${WP_DB_NAME}"
      WP_DB_USER: "${WP_DB_USER}"
      WP_DB_PASSWORD: "${WP_DB_PASSWORD}"
      WP_DB_HOST: "${WP_DB_HOST}"
    restart: on-failure
    networks:
      - inception

  mariadb:
    image: mariadb
    build: ./requirements/mariadb/
    container_name: mariadb
    environment:
      MARIADB_ROOT_PASSWORD: "${MARIADB_ROOT_PASSWORD}"
      MARIADB_DATABASE: "${MARIADB_DATABASE}"
      MARIADB_USER: "${MARIADB_USER}"
      MARIADB_PASSWORD: "${MARIADB_PASSWORD}"
    restart: on-failure
    networks:
      - inception

networks:
  inception:
    name: inception

volumes:
  wp-volume:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: "${VOLUME_PATH}/wordpress"
