#!/bin/sh

chown -R mysql:mysql /var/lib/mysql
if [ ! -d "/var/lib/mysql/${MARIADB_DATABASE}" ]; then
  service mysql start

  mysql -u root -e "CREATE DATABASE IF NOT EXISTS ${MARIADB_DATABASE} DEFAULT CHARACTER SET utf8;"
  mysql -u root -e "CREATE USER '${MARIADB_USER}'@'%' IDENTIFIED BY '${MARIADB_PASSWORD}';"
  mysql -u root -e "GRANT ALL PRIVILEGES ON ${MARIADB_DATABASE}.* TO ${MARIADB_USER}@'%'"
  mysql -u root -e "FLUSH PRIVILEGES;"
  mysqladmin -u root password "${MARIADB_ROOT_PASSWORD}"

  service mysql stop
fi

/usr/bin/mysqld_safe
