#!/bin/sh

set -xe

# Change ownership of the MySQL data directory
chown -R mysql:mysql /var/lib/mysql

if [ ! -d "/var/lib/mysql/${MARIADB_DATABASE}" ]; then
    mysql_install_db --user=mysql --datadir="/var/lib/mysql" >/dev/null

    service mysql start

    mysql --user="$MARIADB_ROOT_USER" --password=""<<EOF
      CREATE DATABASE ${MARIADB_DATABASE};
      USE ${MARIADB_DATABASE};
      GRANT ALL ON *.* TO '${MARIADB_USER}'@'%' IDENTIFIED BY '${MARIADB_PASSWORD}';
      GRANT ALL ON *.* TO '${MARIADB_USER}'@'localhost' IDENTIFIED BY '${MARIADB_PASSWORD}';
      FLUSH PRIVILEGES;
      DELETE FROM mysql.user WHERE user='';
      DELETE FROM mysql.user WHERE user='$MARIADB_ROOT_USER' AND host NOT IN('localhost', '127.0.0.1', '::1');
      DROP DATABASE IF EXISTS tests;
      DELETE FROM mysql.db WHERE Db='test' OR Db='test\\_%';
      FLUSH PRIVILEGES;
      ALTER USER '$MARIADB_ROOT_USER'@'localhost' IDENTIFIED BY '${MARIADB_ROOT_PASSWORD}';
      FLUSH PRIVILEGES;
EOF
    sed -i "s/password =/&${MARIADB_ROOT_PASSWORD}/g" /etc/mysql/debian.cnf
    service mysql stop
fi

/usr/bin/mysqld_safe --user=mysql --datadir=/var/lib/mysql
