#!/bin/bash

set -xe

if [ ! -f ./wp-config.php ]; then
  find . -type f -not -name 'wp_setup' -delete

  wp core download --allow-root

  wp core config \
      --dbname="$WP_DB_NAME" \
      --dbuser="$WP_DB_USER" \
      --dbpass="$WP_DB_PASSWORD" \
      --dbhost="$WP_DB_HOST" \
      --allow-root

   wp core install \
       --url="hmiguel-.42.fr" \
       --title="INCEPTION" \
       --admin_user="hmiguel-" \
       --admin_password="$WP_DB_PASSWORD" \
       --admin_email="hmiguel-@student.42sp.org.br" \
       --allow-root

    wp user create "user42" "user42@blazingly-fast.com" --user_pass="$WP_DB_PASSWORD" --porcelain --role=editor --allow-root
fi

exec "$@"
