#!/bin/bash

set -xe

if [ ! -f ./wp-config.php ]; then
  find . -type f -not -name 'wp_setup' -delete

  wp core download --allow-root

  wp core config \
      --dbname="$MARIADB_DATABASE" \
      --dbuser="$MARIADB_USER" \
      --dbpass="$MARIADB_PASSWORD" \
      --dbhost="$MARIADB_HOST" \
      --allow-root

   wp core install \
       --url="hmiguel-.42.fr" \
       --title="INCEPTION" \
       --admin_user="$MARIADB_USER" \
       --admin_password="$MARIADB_PASSWORD" \
       --admin_email="$ADMIN_EMAIL" \
       --allow-root

    wp user create "$USER2" "$USER2_EMAIL" --user_pass="$MARIADB_PASSWORD" --porcelain --role=editor --allow-root
fi

exec "$@"
