#!/bin/bash

set -xe

if [ ! -f ./wp-config.php ] ; then
  wp core download --allow-root && mv wp-config-sample.php wp-config.php

  # Sets the value of a specific constant or variable defined in wp-config.php file
  wp config set DB_NAME "$WP_DB_NAME" --allow-root
  wp config set DB_USER "$WP_DB_USER" --allow-root
  wp config set DB_PASSWORD "$WP_DB_PASSWORD" --allow-root
  wp config set DB_HOST "$WP_DB_HOST" --allow-root
fi

exec "$@"
